### ISSUE TITLE
Remove copyright notice

### ISSUE THREAD

**Issue by cdbalaji** [CodeDrills-CD/codedrills-recommender#1]
Remove the notice that appears on the footer as this is now open source.

<img width="366" alt="image" src="https://user-images.githubusercontent.com/110294734/194767044-57e4474f-d00b-4eef-9cd9-ae1b837f101f.png">

Place to remove: https://github.com/CodeDrills-CD/codedrills-recommender/blob/master/src/main/resources/templates/common/tail.ftl

Instead of the notice, add "Supported by CodeDrills" where codedrills links to https://codedrills.io/

**Comment by manav-06** [comment]
Hi. You can assign this to me

**Comment by cdbalaji** [comment]
@manav-06 this issue is already taken. You can work on any of the other unassigned issues.
