### ISSUE TITLE
Remove About page

### ISSUE THREAD

**Issue by cdbalaji** [CodeDrills-CD/codedrills-recommender#18]
Remove the about page and its link.

Page: https://github.com/CodeDrills-CD/codedrills-recommender/blob/master/src/main/resources/templates/about.ftl
Also remove link on navbar and tail

**Comment by vsiddharth365** [comment]
Please assign this issue to me.

**Comment by cdbalaji** [comment]
@vsiddharth365 Done!

**Comment by ankur-kayal** [comment]
@vsiddharth365 any updates about the progress of this task? If you are not currently working on it we can assign someone this task.

**Comment by vsiddharth365** [comment]
> @vsiddharth365 any updates about the progress of this task? If you are not currently working on it we can assign someone this task.

Ok, assign it to someone else.

**Comment by manav-06** [comment]
@ankur-kayal you can assign this to me

**Comment by ankur-kayal** [comment]
sure thing

**Comment by manav-06** [comment]
@ankur-kayal @cdbalaji please review #33
