### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by cdbalaji** [CodeDrills-CD/codedrills-recommender#21]
Add target folder, swp files, etc. 

Use https://github.com/github/gitignore/blob/main/Java.gitignore for inspiration.

Add target and .idea folders in addition to those.

**Comment by ssghait007** [comment]
@cdbalaji I have Added PR for this 
https://github.com/CodeDrills-CD/codedrills-recommender/pull/22

**Comment by cdbalaji** [comment]
Thanks accepted that.
