### ISSUE TITLE
Remove bfscpp pages and links

### ISSUE THREAD

**Issue by cdbalaji** [CodeDrills-CD/codedrills-recommender#3]
The pages at https://recommender.codedrills.io/bfscp and the sub-pages.
Also clean up the slides and config for this.

Files to delete:
https://github.com/CodeDrills-CD/codedrills-recommender/tree/master/src/main/resources/static/slides
https://github.com/CodeDrills-CD/codedrills-recommender/blob/master/src/main/resources/static/bfscp.json
https://github.com/CodeDrills-CD/codedrills-recommender/blob/master/src/main/resources/templates/bfscp.ftl
https://github.com/CodeDrills-CD/codedrills-recommender/blob/master/src/main/resources/templates/bfscp_module.ftl
https://github.com/CodeDrills-CD/codedrills-recommender/blob/master/src/main/java/com/codedrills/service/BFSCPService.java

Also remove the menu item for this from https://github.com/CodeDrills-CD/codedrills-recommender/blob/master/src/main/resources/templates/common/navbar.ftl#L45

**Comment by pushanpore014** [comment]
Can I work on this issue
