### ISSUE TITLE
Frequently gives "Oops! Something went wrong while processing your request" on recommender.

### ISSUE THREAD

**Issue by TahseenSust** [CodeDrills-CD/codedrills-recommender#41]
I was trying to use codedrills recommender for last few days but it is not working. It always shows "Oops! Something went wrong while processing your request.".

**Comment by ankur-kayal** [comment]
Aware of this issue, working on a fix.

**Comment by ankur-kayal** [comment]
@TahseenSust can you check if the issue is resolved or not?

**Comment by TahseenSust** [comment]
@ankur-kayal  yes the is fixed for now. Thanks
