### ISSUE TITLE
Create new announcement

### ISSUE THREAD

**Issue by cdbalaji** [CodeDrills-CD/codedrills-recommender#7]
Create a new announcement for the open source project, replacing the "We have launched" announcement shown currently. 

Place to modify: https://github.com/CodeDrills-CD/codedrills-recommender/blob/9d11747e6182a8bfdff85782f5c0d8c04ff02313/src/main/resources/templates/recommender.ftl

**Comment by ryuusama09** [comment]
Hi , @cdbalaji . I can do this , but can you specify what exact changes do you want ?

**Comment by cdbalaji** [comment]
Announcement:

> CodeDrills recommender is now open source! Visit the GitHub repository to contribute or report issues and feature requests.

GitHub repository phrase should link to this repo.
