### ISSUE TITLE
Remove analytics and ad code

### ISSUE THREAD

**Issue by cdbalaji** [CodeDrills-CD/codedrills-recommender#8]
Remove any google ads and analytics code from https://github.com/CodeDrills-CD/codedrills-recommender/blob/master/src/main/resources/templates/common/head.ftl

**Comment by darshancool25** [comment]
Hi @cdbalaji you can assign this one to me. Will take it up once I am able to get setup up and running in Local.

**Comment by cdbalaji** [comment]
@darshancool25 assigned, thanks!

**Comment by ankur-kayal** [comment]
@darshancool25 please follow the contributing.md file updated recently for steps to follow while setting it up locally.

**Comment by ankur-kayal** [comment]
reassigning this issue to @pushanpore014 since it has been inactive for more than 2 weeks.

**Comment by pushanpore014** [comment]
Sure I can work on it

**Comment by ankur-kayal** [comment]
@pushanpore014 assigned
