### ISSUE TITLE
Update FAQs

### ISSUE THREAD

**Issue by cdbalaji** [CodeDrills-CD/codedrills-recommender#9]
Update to current information.
Remove amazon affiliate links.

https://github.com/CodeDrills-CD/codedrills-recommender/blob/9d11747e6182a8bfdff85782f5c0d8c04ff02313/src/main/resources/templates/faq.ftl

**Comment by ryuusama09** [comment]
hi @cdbalaji , i would like to work on this issue

**Comment by cdbalaji** [comment]
@ryuusama09 assigned to you. Thanks!

**Comment by ryuusama09** [comment]
@cdbalaji , regarding the amazon links for the books , should i remove that entire question , or just remove the link property from book's names

**Comment by cdbalaji** [comment]
@ryuusama09 you can remove the question itself.

**Comment by cdbalaji** [comment]
I wonder if we should modify it some more. #20 only removed the links. How about:

* Adding atcoder in the [What are the best sites to practice in?](https://recommender.codedrills.io/faq#cp4)
* Add python to [Which programming language is the best one for competitive programming?](https://recommender.codedrills.io/faq#cp3)
* And anything else that you can think of

**Comment by ankur-kayal** [comment]
@ryuusama09 any updates on this issue?

**Comment by ryuusama09** [comment]
hey @ankur-kayal , the first part of the issue had been done , but somehow i didnt recieve  the notification for the second part . As you see ,now i realized that more has been asked . I shall do it . Thank you for your concern !

**Comment by ankur-kayal** [comment]
@ryuusama09 can you please link this issue whenever you open a pull request for this? I thought this was not worked upon as it was not tracked and is still open.
